### ISSUE TITLE
[AUX_SHM] Semaphore Deadlock Issue

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/c-runtime#15]
On executor process exit, sometimes the robot description semaphore `rd_sem` will be in the locked state. This causes issue when the process next starts as it will post and deadlock forever. We currently have a workaround which will post the semaphore on `aux_shm_stop` but this solution doesn't solve the original problem.

**Comment by benliao1** [comment]
Will also try to investigate this in my shared memory investigations~~
