### ISSUE TITLE
Script to print out current SHM and Aux SHM values

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/c-runtime#24]
This script would be very useful now to check that the net handler and dev handler are working.

**Comment by benliao1** [comment]
Was I going to do this? Or @AVSurfer123 ? Also perhaps not necessary due to the `print_gamepad_state()` and `print_robot_desc` functions in Aux SHM, and the `print_catalog`, `print_params`, and `print_dev_ids` functions in SHM.

**Comment by AVSurfer123** [comment]
No, I can do it. I just wanted an executable file that I can run to tell me it. Takes like 2 lines
