### ISSUE TITLE
[LOWCAR] add support for a new LOG packet type

### ISSUE THREAD

**Issue by benliao1** [pioneers/c-runtime#30]
The code in `lowcar/lib` (i.e. the lowcar code on the Arduino devices themselves) should support sending a LOG packet from the device to Device Handler, which could then be translated to a log message in runtime and sent to Dawn or Shepherd. Should probably be implemented in the `Device` class.

**Comment by AVSurfer123** [comment]
This can be done by the device handler just calling `log_printf` with the packet's contents rights?

**Comment by benliao1** [comment]
Right, once it gets to the device handler, it should be easy to do. The hard part is implementing it in the lowcar code...
