### ISSUE TITLE
[LOWCAR] Flash script

### ISSUE THREAD

**Issue by benliao1** [pioneers/c-runtime#42]
Write a new flash script that assumes lowcar library installed somewhere on the system, and assumes Arduino already downloaded onto the computer, and allows a command like `./flash.sh` to flash to the Arduino board successfully.

This is going to be HARD and will likely require lots and lots and lots of debugging and will probably never work completely. :\

**Comment by AVSurfer123** [comment]
We can use `arduino-cli` to do this extremely easily now.
