### ISSUE TITLE
[DEV_HANDLER][LOGGER] Dev Handler receives 0x0A instead of 0x0D from Lowcar

### ISSUE THREAD

**Issue by levincent06** [pioneers/c-runtime#45]
- Check if it's just the byte 0x0D that is problematic
- Check if this is a software issue and not hardware

**Comment by AVSurfer123** [comment]
@kaqqy fixed the bug in `dev_handler`. Reason was due to the serial port not being configured for carriage return and new line. (0xA is new line and 0xD is carriage return)
