### ISSUE TITLE
[LOGGER] Logging with PYTHON level doesn't work

### ISSUE THREAD

**Issue by AVSurfer123** [pioneers/c-runtime#55]
Python errors aren't getting sent over the network properly, with many lines being cut out.

**Comment by benliao1** [comment]
We found an issue similar to this (except it was double printing) in `dev_handler`
Perhaps try copy-pasting the `logger.c` and `logger.h` files in the newest commit on `dev_handler` branch and see if that fixes this problem (we added a mutex to make sure logs are being emitted one at a time, there was no synchronization check before)

**Comment by benliao1** [comment]
Fixed, I think! With edit above

**Comment by AVSurfer123** [comment]
This was caused by adding an extra byte for the null character when the logger sends data to the log FIFO. We don't want to send the null character due to how `fgets` works.
